import Head from "next/head";
import { Box, Button, Typography } from "@mui/material";
import { useTheme } from "@/context/ThemeProvider";
import Categorylist from "@/components/category";
import useMediaQuery from "@mui/material/useMediaQuery";
import { StyledHome } from "../components/Home.styled";
import SideBar from "@/sidebar/SideBar";

//React icons
import {
  IoGameControllerOutline,
  IoMusicalNotesOutline,
  IoTrophyOutline,
  IoMicOutline,
} from "react-icons/io5";

// Mobile Components
import BigChannels from "../components/Channels/ChannelsMobile/BigChannels";
import SmallCategories from "../components/Categories/CategoriesMobile/SmallCategories";

// Desktop Components
import Slide from "../components/Share/Slide";
import ChannelsDesktop from "../components/Channels/ChannelsDesktop/ChannelsDesktop";
import CategoriesDesktop from "../components/Categories/CategoriesDesktop/CategoriesDekstop";
import Tags from "../components/Share/Tags";

import ShowMore from "../components/Share/ShowMore";

export default function Index() {
  const { theme, changeTheme } = useTheme();
  const matches = useMediaQuery("(min-width:1250px)");
  const dis = useMediaQuery("(min-width:819px)");

  return (
    <Box
      sx={{
        backgroundColor: theme === "white" ? "black" : "white",
        height: "100vh",
        width: "100vw",
      }}
    >
      <Head>
        <title>Live Stream</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <StyledHome>{dis ? <SideBar /> : <Box />}</StyledHome>
    </Box>
  );
}
